auth { type = "dev" }

oras { insecure = true }

boot { token = "changeme" }

keeper {
  instance-id = 6
  parallelism = 4

  database { path = "/tmp/tkeeper/db" }

  audit {
    enabled = true
    file { directory = "/tmp/tkeeper/audit" }
  }

  providers {
    selected = "shamir"
    shamir { total = 5, threshold = 3 }
  }

  server {
    public { host = "0.0.0.0", port = 8080 }
    internal { host = "0.0.0.0", port = 9090 }
  }

  peers = [
    { id = 1, internal-url = "http://keeper-4:9090" },
    { id = 2, internal-url = "http://keeper-5:9090" }
  ]
}
