plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

rootProject.name = 'tkeeper'

include 'integration-tests'
include 'sdk'
include 'integration-tests:functional'
include 'integration-tests:performance'
include 'features:seal-aws'
include 'features:seal-gcloud'
include 'features:authority-bitcoin'
include 'features:authority-evm'
include 'features:authority-x509'
include 'features:ecies'
include 'features:ui'
include 'integration-tests:failure-injection'

include 'platform-ecc'
include 'platform-pqc'

include 'features:auth-dev'

include 'features:recovery'
include 'features:recovery:ecc'
include 'features:recovery:pqc'

include 'features:dry-run'

include 'features:agentic-payments'