auth {
  type = ${?KEEPER_AUTH_TYPE}
}

boot {
  token = ${?KEEPER_BOOT_TOKEN}
}

keeper {
  recovery = false
  recovery = ${?KEEPER_RECOVERY}

  database {
    path = "data/keeper.db"
    path = ${?KEEPER_DATABASE_PATH}
  }

  audit {
    enabled = false
    enabled = ${?KEEPER_AUDIT_ENABLED}
  }

  authority {
    arbitrary {
      enabled = false
      enabled = ${?KEEPER_AUTHORITY_ARBITRARY_ENABLED}
    }
  }

  client {
    tls = false
    tls = ${?KEEPER_CLIENT_TLS}

    request-timeout = 30000
    request-timeout = ${?KEEPER_CLIENT_REQUEST_TIMEOUT}

    trust-store-path = ${?KEEPER_CLIENT_TRUST_STORE_PATH}
    trust-store-password = ${?KEEPER_CLIENT_TRUST_STORE_PASSWORD}
    trust-store-type = ${?KEEPER_CLIENT_TRUST_STORE_TYPE}

    key-store-path = ${?KEEPER_CLIENT_KEY_STORE_PATH}
    key-store-password = ${?KEEPER_CLIENT_KEY_STORE_PASSWORD}
    key-store-type = ${?KEEPER_CLIENT_KEY_STORE_TYPE}
  }

  ssl {
    enabled = false
    enabled = ${?KEEPER_SSL_ENABLED}

    trust-store-path = ${?KEEPER_SSL_TRUST_STORE_PATH}
    trust-store-password = ${?KEEPER_SSL_TRUST_STORE_PASSWORD}
  }

  providers {
    selected = "shamir"
    selected = ${?KEEPER_SEAL_SELECTED}

    shamir {
      total = 3
      total = ${?KEEPER_SEAL_SHAMIR_TOTAL}

      threshold = 2
      threshold = ${?KEEPER_SEAL_SHAMIR_THRESHOLD}
    }
  }

  server {
    public {
      host = localhost
      host = ${?KEEPER_HOST}

      port = 8080
      port = ${?KEEPER_PORT}

      idle-timeout = 30s
      idle-timeout = ${?KEEPER_IDLE_TIMEOUT}

      max-request-length = 10485760
      max-request-length = ${?KEEPER_MAX_REQUEST_LENGTH}

      tls {
        enabled = false
        enabled = ${?KEEPER_TLS_ENABLED}

        key-store-path = ${?KEEPER_TLS_KEY_STORE_PATH}
        key-store-password = ${?KEEPER_TLS_KEY_STORE_PASSWORD}
        key-store-type = ${?KEEPER_TLS_KEY_STORE_TYPE}

        certificate-chain-path = ${?KEEPER_TLS_CERT_CHAIN_PATH}
        private-key-path = ${?KEEPER_TLS_PRIVATE_KEY_PATH}
        private-key-password = ${?KEEPER_TLS_PRIVATE_KEY_PASSWORD}
      }
    }

    internal {
      host = localhost
      host = ${?KEEPER_INTERNAL_HOST}

      port = 9090
      port = ${?KEEPER_INTERNAL_PORT}

      idle-timeout = 30s
      idle-timeout = ${?KEEPER_INTERNAL_IDLE_TIMEOUT}

      max-request-length = 10485760
      max-request-length = ${?KEEPER_INTERNAL_MAX_REQUEST_LENGTH}

      tls {
        enabled = false
        enabled = ${?KEEPER_INTERNAL_TLS_ENABLED}

        key-store-path = ${?KEEPER_INTERNAL_TLS_KEY_STORE_PATH}
        key-store-password = ${?KEEPER_INTERNAL_TLS_KEY_STORE_PASSWORD}
        key-store-type = ${?KEEPER_INTERNAL_TLS_KEY_STORE_TYPE}

        client-auth = false
        client-auth = ${?KEEPER_INTERNAL_TLS_CLIENT_AUTH}
        trust-store-path = ${?KEEPER_INTERNAL_TLS_TRUST_STORE_PATH}
        trust-store-password = ${?KEEPER_INTERNAL_TLS_TRUST_STORE_PASSWORD}
        trust-store-type = ${?KEEPER_INTERNAL_TLS_TRUST_STORE_TYPE}

        certificate-chain-path = ${?KEEPER_INTERNAL_TLS_CERT_CHAIN_PATH}
        private-key-path = ${?KEEPER_INTERNAL_TLS_PRIVATE_KEY_PATH}
        private-key-password = ${?KEEPER_INTERNAL_TLS_PRIVATE_KEY_PASSWORD}
      }
    }
  }
}
