auth {
  type = ${?KEEPER_AUTH_TYPE}
  type = "dev"
}

boot {
  token = ${?KEEPER_BOOT_TOKEN}
}

keeper {
  database {
    path = ${?KEEPER_DATABASE_PATH}
    path = "data/keeper.db"
  }

  audit {
    enabled = ${?KEEPER_AUDIT_ENABLED}
    enabled = false
  }

  client {
    tls = ${?KEEPER_CLIENT_TLS}
    tls = false

    trust-store-path = ${?KEEPER_CLIENT_TRUST_STORE_PATH}
    trust-store-password = ${?KEEPER_CLIENT_TRUST_STORE_PASSWORD}
  }

  ssl {
    enabled = ${?KEEPER_SSL_ENABLED}
    enabled = false

    trust-store-path = ${?KEEPER_SSL_TRUST_STORE_PATH}
    trust-store-password = ${?KEEPER_SSL_TRUST_STORE_PASSWORD}
  }

  providers {
    selected = ${?KEEPER_SEAL_SELECTED}
    selected = "shamir"

    shamir {
      total = ${?KEEPER_SEAL_SHAMIR_TOTAL}
      total = 3

      threshold = ${?KEEPER_SEAL_SHAMIR_THRESHOLD}
      threshold = 2
    }
  }

  server {
    public {
      host = ${?KEEPER_HOST}
      host = localhost

      port = ${?KEEPER_PORT}
      port = 8080

      idle-timeout = ${?KEEPER_IDLE_TIMEOUT}
      idle-timeout = 30s

      max-request-length = ${?KEEPER_MAX_REQUEST_LENGTH}
      max-request-length = 10485760

      tls {
        enabled = ${?KEEPER_TLS_ENABLED}
        enabled = false

        key-store-path = ${?KEEPER_TLS_KEY_STORE_PATH}
        key-store-password = ${?KEEPER_TLS_KEY_STORE_PASSWORD}
        key-store-type = ${?KEEPER_TLS_KEY_STORE_TYPE}

        certificate-chain-path = ${?KEEPER_TLS_CERT_CHAIN_PATH}
        private-key-path = ${?KEEPER_TLS_PRIVATE_KEY_PATH}
        private-key-password = ${?KEEPER_TLS_PRIVATE_KEY_PASSWORD}
      }
    }

    internal {
      host = ${?KEEPER_INTERNAL_HOST}
      host = localhost
      port = ${?KEEPER_INTERNAL_PORT}
      port = 9090

      idle-timeout = ${?KEEPER_INTERNAL_IDLE_TIMEOUT}
      idle-timeout = 30s

      max-request-length = ${?KEEPER_INTERNAL_MAX_REQUEST_LENGTH}
      max-request-length = 10485760

      tls {
        enabled = ${?KEEPER_INTERNAL_TLS_ENABLED}
        enabled = false

        key-store-path = ${?KEEPER_INTERNAL_TLS_KEY_STORE_PATH}
        key-store-password = ${?KEEPER_INTERNAL_TLS_KEY_STORE_PASSWORD}
        key-store-type = ${?KEEPER_INTERNAL_TLS_KEY_STORE_TYPE}

        certificate-chain-path = ${?KEEPER_INTERNAL_TLS_CERT_CHAIN_PATH}
        private-key-path = ${?KEEPER_INTERNAL_TLS_PRIVATE_KEY_PATH}
        private-key-password = ${?KEEPER_INTERNAL_TLS_PRIVATE_KEY_PASSWORD}
      }
    }
  }
}