keeper {
  dev {
    token = "integration-tests-dev-token"
    permissions = [
      "tkeeper.system.init",
      "tkeeper.dkg.create",
      "tkeeper.key.mcp-allowed.public",
      "tkeeper.key.mcp-allowed.sign",
      "tkeeper.key.mcp-allowed.verify"
    ]
  }
}
