services:
  registry:
    image: registry:2
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

  keeper-1:
    image: exploit/tkeeper:dev
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Djava.library.path=/usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
      LD_LIBRARY_PATH: /usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
    volumes:
      - ./conf/keeper-1:/etc/tkeeper:ro
    tmpfs:
      - /var/lib/tkeeper:rw,exec,nosuid,size=512m,uid=185,gid=0

  keeper-2:
    image: exploit/tkeeper:dev
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Djava.library.path=/usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
      LD_LIBRARY_PATH: /usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
      HSM_ENABLED: "true"
      SOFTHSM2_CONF: /etc/softhsm2/softhsm2.conf
    volumes:
      - ./conf/keeper-2:/etc/tkeeper:ro
    tmpfs:
      - /var/lib/tkeeper:rw,exec,nosuid,size=512m,uid=185,gid=0
      - /var/lib/softhsm/tokens:rw,nosuid,size=64m,uid=185,gid=0

  keeper-3:
    image: exploit/tkeeper:dev
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Djava.library.path=/usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
        -Dkeeper.coordinator.enabled=false
      LD_LIBRARY_PATH: /usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
    volumes:
      - ./conf/keeper-3:/etc/tkeeper:ro
    tmpfs:
      - /var/lib/tkeeper:rw,exec,nosuid,size=512m,uid=185,gid=0

  keeper-4:
    image: exploit/tkeeper:dev
    ports:
      - "8084:8080"
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Djava.library.path=/usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
      LD_LIBRARY_PATH: /usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
    volumes:
      - ./conf/keeper-4:/etc/tkeeper:ro
    tmpfs:
      - /var/lib/tkeeper:rw,exec,nosuid,size=512m,uid=185,gid=0

  keeper-5:
    image: exploit/tkeeper:dev
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Djava.library.path=/usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
      LD_LIBRARY_PATH: /usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
    volumes:
      - ./conf/keeper-5:/etc/tkeeper:ro
    tmpfs:
      - /var/lib/tkeeper:rw,exec,nosuid,size=512m,uid=185,gid=0

  keeper-6:
    image: exploit/tkeeper:dev
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Djava.library.path=/usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
      LD_LIBRARY_PATH: /usr/local/lib:/usr/lib64:/lib64:/lib:/usr/lib
    volumes:
      - ./conf/keeper-6:/etc/tkeeper:ro
    tmpfs:
      - /var/lib/tkeeper:rw,exec,nosuid,size=512m,uid=185,gid=0
