auth { type = "dev" }

oras { insecure = true }

boot { token = "changeme" }

keeper {
  instance-id = 2
  parallelism = 4
  database { path = "/var/lib/tkeeper/db" }

  audit {
    enabled = true
    file { directory = "/var/lib/tkeeper/audit" }
  }

  providers {
    selected = "hsm"

    hsm {
       name = "tkeeper-test"
       library = "/usr/local/lib/softhsm/libsofthsm2.so"
       slot-list-index = 0
       key-alias = "tkeeper-kek"
       cipher = "AES_GCM"
       pin = "softhsm-user"
    }
  }

  server {
    public { host = "0.0.0.0", port = 8080 }
    internal { host = "0.0.0.0", port = 9090 }
  }

  peers = [
    { id = 1, internal-url = "http://keeper-1:9090" },
    { id = 3, internal-url = "http://keeper-3:9090" }
  ]
}
